### ISSUE TITLE
mqtt.js returned premature close error

### ISSUE THREAD

**Issue by bmrpatel** [Azure/azure-iot-sdk-node#21]
# Context
- **OS and version used:** Ubuntu 16
- **Node.js version:** 7.4
- **npm version:** 4.0.5  
- **list of installed packages:** 
 | ── azure-iot-device@1.1.6
├── azure-iot-device-amqp@1.1.6
├── azure-iot-device-mqtt@1.1.6

- **cloned repo:** n/a

# Description of the issue:
Yesterday I started seeing messages on couple of test machines with the following error. Is it due to some hickup on the iothub services or issue with the network? not sure?
- mqtt.js returned premature close error

# Code sample exhibiting the issue:
Get this error on connect. Code was working fine before and seems to be working now.

# Console log of the issue:
connect called, reason: [DISCONNECTED]
connect attempt 1
Connect Error mqtt.js returned Connection refused: Server unavailable error
connect attempt 2
Connect Error mqtt.js returned Connection refused: Server unavailable error
connect attempt 3
Connect Error mqtt.js returned Connection refused: Server unavailable error
connect attempt 4
Connect Error mqtt.js returned Connection refused: Server unavailable error
connect attempt 5
Connect Error mqtt.js returned Connection refused: Server unavailable error
connect attempt 6
Connect Success

I also have some errors in log as follows:
error occured mqtt.js returned premature close error

If this error is expected please let me know a way to handle it. 

Thanks

**Comment by bmrpatel** [comment]
I also see this error:
mqtt.js returned Connection refused: Not authorized error

When do I get this error?

Thanks

**Comment by jdneo** [comment]
I also met this error. same as @bmrpatel described

**Comment by pierreca** [comment]
@bmrpatel @jdneo can we get the iothub name and the time (or time frame) at which you saw the errors?

**Comment by jdneo** [comment]
I saw this error just couple minutes ago. Just running the [sample code](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js) can reproduce the error.

**Comment by pierreca** [comment]
@bmrpatel @jdneo hub names and timestamps help because we can check the logs - also can you confirm if it's over MQTT over TLS (Mqtt transport object)) or MQTT over WSS (Secure websockets, MqttWs transport object)?

**Comment by jdneo** [comment]
**hub name:** h5-sample-app
**timestamps:** sorry I can not give the precise timestamps. It happened about 
Mar 09 2017 10:00:00 - 12:00:00 GMT+0800 (China Standard Time) I think.
**protocal:** Mqtt transport object

The device client will receive 'disconnect' event once it is connected. I can see 'Client connected' repeat showing in the console log if I run the [sample code](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js). And This log: 'error occured mqtt.js returned premature close error' can also be seen.

I ran the sample code just now, seems the issue has been recovered. The device client won't receive disconnect event once the connection is established.

**Comment by bmrpatel** [comment]
2017-03-08 T18:27:50.350Z
2017-03-08 T19:36:34.334Z
sometime after 2017-03-08 T22:59:04.899Z, I saw mqtt.js returned Connection refused: Not authorized error

Can I PM the hub details?

**Comment by pierreca** [comment]
@bmrpatel @jdneo we've identified a problem and are deploying a fix. will keep you posted of the deployment.

**Comment by pierreca** [comment]
The fix has been deployed, you shouldn't be seeing this issue anymore. Since it's a service thing, no code change or SDK update needed. Thanks a lot for your patience!

**Comment by bmrpatel** [comment]
Thank you @pierreca

**Comment by snobu** [comment]
Has this fix reached Azure West Europe yet?

Still getting this:
```
UnauthorizedError: mqtt.js returned Connection refused: Not authorized error
```
Timestamp: 09:15 -> 09:20 UTC March 29 2017

Worked a few weeks ago (everything was fine on March 10, 2017 for example).

**Comment by pierreca** [comment]
Yes that fix has been deployed everywhere - can you open a new issue with the description of what is happening? it's likely the same error but a different cause

**Comment by ravinleague** [comment]
The issue still exists.
{ [Error: EIO, Input/output error] errno: 5, code: 'EIO', syscall: 'writeByte' }
[IoT hub Client] Connect error: mqtt.js returned Connection refused: Not authorized error

Deploy location: Australia South East

**Comment by pierreca** [comment]
@ravinleague that looks like a different error. Please open a new issue and follow the issue template for us to have as much context as possible when looking at it, thanks!

**Comment by dushyantbangal** [comment]
Looks like someone someone is getting similar error again:
https://stackoverflow.com/questions/49316395/node-js-azure-iot-hub-mqtt-error
